# syntax=docker.io/docker/dockerfile:1

FROM node:20-alpine AS dev
WORKDIR /app

RUN apk add --no-cache libc6-compat

# Install dependencies
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
  else echo "Lockfile not found." && exit 1; \
  fi

# Copy source
COPY . .

ENV NODE_ENV=development
ENV HOSTNAME="0.0.0.0"
EXPOSE 3000

CMD ["npx", "next", "dev"]
